# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    providers:
        in_memory:
            memory:
                users:
                    lambda:
                        password: $2y$12$S7SbMeyZFQQbttsIDaXeBeYK57aSksToUxWEMDeJlnTpoEy1x.2KK #lambdapass
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$12$McnRkN6Xyxnfwdu50V.qgeMpS1jU0KyDQ1ET8Gaax6H5GggPV2PRG #user
                        roles: 'ROLE_ADMIN'
#                    johlamie:
#                        password: $2y$12$McnRkN6Xyxnfwdu50V.qgeMpS1jU0KyDQ1ET8Gaax6H5GggPV2PRG #user
#                        roles: 'ROLE_ADMIN'


    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout: true



    access_control:
        # chemin accessible avec une connexion annonyme
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }


        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }


        # chemin accessible avec une connexion utilisateur
        - { path: ^/Origine, roles: ROLE_USER }
        - { path: ^/vin, roles: ROLE_USER }
        - { path: ^/Vin, roles: ROLE_USER }
        - { path: ^/Bouteille, roles: ROLE_USER }