<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLedqrow\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLedqrow/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLedqrow.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLedqrow\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLedqrow\appDevDebugProjectContainer([
    'container.build_hash' => 'Ledqrow',
    'container.build_id' => '92b621c9',
    'container.build_time' => 1562771639,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLedqrow');
